* elastic-backup-2s3 -- Snapshot, Backup, and Restore Elasicsearch Indicies to and from S3
  
  When you have an itch to scratch...

  I simply want to be able to control the backup and
  restoration of the Elasticsearch cluster to S3
  without any fuss or having to dilly around with
  curl -XPUTS and friends.

  So here it is, and I make no apologies about not 
  supporting the "shared volume" option of Elasticsearch
  snapshots. I may add support at a later date. Or
  feel free to add it and do a pull request.

  There are many features I wish to add to this, and
  if you have any suggestions, please feel free to send
  them my way!

** Overview
   Elastic Backup simply allows you to specifiy some
   or all of the indicies, some target bucket, and 
   run the backup / snapshot.

   It hides all the sordid details about "registration"
   and the like, and will optionally clean up behind 
   itself and remove the registration if you did not
   specify a name for the registration.

** TODO Documentation
   Documentation is comming. Basically,
   just running the command without any parameters
   will give you some basic usage. 

*** S3URL format
    We adopt a convention to make it easy for you
    to specify the S3 bucket, path, and snapshot
    name stored in the bucket. The S3 URL format is:

    s3://AWS_S3_BUCKET/path/in/bucket:SNAPSHOT

    In some cases, :SNAPSHOT is optional, but usually
    expected to be there.

** Examples
   To backup/snapshot your ES to S3
   and wait until the backup is completed:
   #+BEGIN_SRC bash
   es-snapshot snapshot localhost s3://your-backup-bucket/your-backup-path:snap_1 -v2 -w
   #+END_SRC
   
   The default repository of 'elastic-backup' is used.
   To specify your own repository name:
   #+BEGIN_SRC bash
   es-snapshot snapshot localhost s3://your-backup-bucket/your-backup-path:snap_1 -v2 -w --repo your-repo-name
   #+END_SRC


   To backup/snapshot two indices index1 and index2:
   #+BEGIN_SRC bash
   es-snapshot snapshot localhost s3://your-backup-bucket/your-backup-path:snap_1 -v2 -w --indices index1 index2
   #+END_SRC

   To restore your snapshot
   #+BEGIN_SRC bash
   es-snapshot restore s3://your-backup-bucket/your-backup-path:snap_1 localhost -v2 -w
   #+END_SRC

   To restore your snapshot using your-repo-name:
   #+BEGIN_SRC bash
   es-snapshot restore s3://your-backup-bucket/your-backup-path:snap_1 localhost -v2 -w --repo your-repo-name
   #+END_SRC
   
   You may specify --dryrun (-u) to see the JSON that will
   be sent without actually executing the commands. Also
   -v2 will show you the same while allowing your 
   commands to execute.

   To see the status of your snapshots:
   #+BEGIN_SRC bash
   es-snapshot list status localhost
   #+END_SRC

   To see a list of your indices:
   #+BEGIN_SRC bash
   es-snapshot list indices localhost
   #+END_SRC

** Scratchpad
   My own personal notes on this project. These
   are not gauranteed to be useful to you nor 
   up-to-date.

** Contributing to elastic-backup-2s3

+ Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
+ Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
+ Fork the project.
+ Start a feature/bugfix branch.
+ Commit and push until you are happy with your contribution.
+ Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
+ Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2016 Fred Mitchell. See LICENSE.txt for
   further details.
