* elastic-backup-2s3 -- Snapshot, Backup, and Restore Elasicsearch Indicies to and from S3
  
  When you have an itch to scratch...

  I simply want to be able to control the backup and
  restoration of the Elasticsearch cluster to S3
  without any fuss or having to dilly around with
  curl -XPUTS and friends.

  So here it is, and I make no apologies about not 
  supporting the "shared volume" option of Elasticsearch
  snapshots. I may add support at a later date. Or
  feel free to add it and do a pull request.

** TODO Overview
** TODO Documentation
** TODO Examples
** Contributing to elastic-backup-2s3

+ Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
+ Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
+ Fork the project.
+ Start a feature/bugfix branch.
+ Commit and push until you are happy with your contribution.
+ Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
+ Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2016 Fred Mitchell. See LICENSE.txt for
   further details.
